### ISSUE TITLE
Using local database instead of HTTP API

### ISSUE THREAD

**Issue by h4cc** [navinpeiris/geoip#1]
How about using the maxmind files directly, instead of freegeoip.net?

Example: https://maxmind.github.io/MaxMind-DB/

**Comment by navinpeiris** [comment]
Hi @h4cc, there's already another project [geolix](https://github.com/mneudert/geolix) that uses the MaxMind DB files directly, which is recommended if that's what you prefer.

The motivation behind this one is to make it easy to use your own FreeGeoIP installation, which can be very easily deployed using docker etc, but is defaulted to use the free service if you don't need all that.

**Comment by h4cc** [comment]
Thanks for that info. Maybe having a strategy for freegeoip or geolix would be cool.

As far as i can see, geolix does not have a integration for Plug.Conn

**Comment by iloveitaly** [comment]
Closing this out, documented Geolix usage for maxmind DB files directly in the readme https://github.com/navinpeiris/geoip/commit/a75080dd13b5afe065e2d54e222ff49c963dd31b
