### ISSUE TITLE
Geoip logo

### ISSUE THREAD

**Issue by batarian71** [navinpeiris/geoip#10]
Hi,

I guess geoip does not have a logo. I can design a logo for it. What do you think?

**Comment by navinpeiris** [comment]
Oh wow!

Just to make sure we're on the same page, I can't afford to pay you for it but will of course acknowledge you as the creator of the logo in the README etc if we do decide to go with one you come up with.

If you're ok with that, would love to see some concepts! Thanks @batarian71!

**Comment by batarian71** [comment]
I just want to make a contribution. It was designed from the first letter and function of the application.  Also, If there is something you want, I can design it.

![geoip](https://user-images.githubusercontent.com/36008612/40665042-ecce7054-6364-11e8-96c3-4657de83a1af.jpg)

**Comment by navinpeiris** [comment]
oh wow! Love it!!

If possible, can we get this with a transparent background instead of the white one @batarian71?

**Comment by batarian71** [comment]
Ofcourse. i will send png version with pr. Please say me which color you like.

**Comment by navinpeiris** [comment]
Awesome, thanks! Would love to go with the purple one, considering this is an elixir project and just to reinforce that aspect as well.

**Comment by batarian71** [comment]
I sent a pr :) https://github.com/navinpeiris/geoip/pull/11 please tell me if you need a logo for another project. Thanks!

**Comment by navinpeiris** [comment]
Awesome, thanks a bunch for that @batarian71, really appreciate it! ❤️ 

As promised, I've included an acknowledgement in the README: https://github.com/navinpeiris/geoip/commit/9c05b59a35aff5d7c758d12da6a90207283ec526

I've also got a few other elixir projects here that you could checkout if you wanted to contribute to:
* https://github.com/navinpeiris/logster
* https://github.com/navinpeiris/ex_unit_notifier
* https://github.com/navinpeiris/countriex
