### ISSUE TITLE
Doesn't Support IPv6

### ISSUE THREAD

**Issue by xanderdunn** [navinpeiris/geoip#5]
When I do `GeoIP.lookup("2001:0db8:85a3:0000:0000:8a2e:0370:7334")` or any other example v6 address, I get empty results .

**Comment by navinpeiris** [comment]
HI @xanderdunn, sorry for the late response. I just tested this ip address out at freegeoip.net, and seems like it's returning empty results, which is what this package parses. (See: https://freegeoip.net/json/2001:0db8:85a3:0000:0000:8a2e:0370:7334)

If you think this is in error, might be worthwhile raising an issue there?

If you want to test out an instance where an IPv6 address returns results, checkout: `GeoIP.lookup("2404:6800:4008:c00::71")`
